#!/usr/bin/env python3
"""
build_data.py -- regenerate the embedded data block of the picker
script (assets/js/picker.js) from the live Docker Hub repositories.

Run manually:      python3 site/build_data.py [path/to/picker.js]
Run by CI weekly:  see .github/workflows/site.yml

What it rewrites (everything between @@DATA-START@@ and @@DATA-END@@):
  BUILD_STAMP    today's date (UTC)
  DATA           every selectable image, parsed from the repository names
                 `sscng/stata<ver>[-<edition>[-<flavor>]]` and their tags

Repository names are parsed, not listed by hand, so a new Stata version,
a new flavor suffix or a new tag shows up on the next build. Only tags that
are build dates (YYYY-MM-DD) or `latest` are kept: `test` and rescue tags
such as `2026-04-14-24.04` are not meant to be pulled.

Exits 0 with "unchanged" if the block is already current.
"""
import datetime as dt
import json
import re
import sys
import time
import urllib.request
from pathlib import Path

HUB = "https://hub.docker.com/v2/repositories/sscng/"
MARK_A, MARK_B = "/* @@DATA-START@@", "/* @@DATA-END@@ */"
TAG_OK = re.compile(r"^(\d{4}-\d{2}-\d{2}|latest)$")
# stata19, stata19_5, stata18now, stata19-se, stata19_5-se-i-python, ...
REPO = re.compile(
    r"^stata(?P<major>\d+)(?:_(?P<minor>\d+)|(?P<now>now))?"
    r"(?:-(?P<ed>base|be|se|mp)(?:-(?P<flavor>.+))?)?$")


def get(url: str) -> dict:
    for attempt in range(4):
        try:
            with urllib.request.urlopen(url, timeout=30) as fh:
                return json.load(fh)
        except Exception:
            if attempt == 3:
                raise
            time.sleep(2 ** attempt)


def paged(url: str):
    while url:
        page = get(url)
        yield from page["results"]
        url = page.get("next")


def parse(name: str):
    """Return (version key, edition, flavor) for a selectable repository,
    or None. Edition "all" is the pre-split monolithic image."""
    m = REPO.fullmatch(name)
    if not m or m["ed"] == "base":
        return None
    major = int(m["major"])
    if m["minor"]:
        key, order, label = f"{major}_{m['minor']}", (major, int(m["minor"])), f"Now {major}"
    elif m["now"]:
        # legacy monolithic repo for StataNow, from before the _5 naming
        key, order, label = f"{major}now", (major, 2), f"Now {major} (early)"
    else:
        key, order, label = str(major), (major, 0), str(major)
    return key, order, label, m["ed"] or "all", m["flavor"] or ""


def collect() -> dict:
    versions = {}
    for repo in paged(HUB + "?page_size=100"):
        name = repo["name"]
        parsed = parse(name)
        if not parsed:
            continue
        key, order, label, ed, flavor = parsed
        tags = sorted((t["name"] for t in paged(f"{HUB}{name}/tags?page_size=100")
                       if TAG_OK.match(t["name"])), reverse=True)
        if not tags:
            continue
        v = versions.setdefault(key, {"key": key, "label": label,
                                      "order": list(order), "editions": {}})
        v["editions"].setdefault(ed, {})[flavor] = tags
    out = sorted(versions.values(), key=lambda v: v["order"], reverse=True)
    for v in out:
        del v["order"]
    return {"versions": out}


def render(data: dict) -> str:
    return (f"{MARK_A} -- regenerated by build_data.py; do not edit by hand */\n"
            f'const BUILD_STAMP = "{dt.datetime.now(dt.timezone.utc).date()}";\n'
            f"const DATA = {json.dumps(data, separators=(',', ':'))};\n"
            f"{MARK_B}")


def main(path: Path) -> int:
    text = path.read_text(encoding="utf-8")
    a, b = text.index(MARK_A), text.index(MARK_B) + len(MARK_B)
    old = text[a:b]
    # keep the old stamp when only the date changed, so reruns are idempotent
    new = render(collect())
    strip = lambda s: re.sub(r'BUILD_STAMP = "[^"]*"', "", s)
    if strip(old) == strip(new):
        print("unchanged")
        return 0
    path.write_text(text[:a] + new + text[b:], encoding="utf-8")
    print(f"updated {path}")
    return 0


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    sys.exit(main(Path(sys.argv[1]) if len(sys.argv) > 1 else here / "assets/js/picker.js"))
